version: "3"
services:
  redis-host:
    image: redis
    ports:
      - "6379:6379"
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"
  mongo-host:
    image: mongo
    ports:
    - "27017:27017"
  api:
    build: ./express-lab
    ports:
    - "3009:3009"
    command: node index.js
    depends_on:
    - mongo-host
    - redis-host
  web:
    build: ./proygames
    ports:
    - "8000:80"
    links:
    - api